version: "3"

services:
 #Sinatra SampleApplication
 app:
#   entrypoint: /docker-entrypoint.sh
   build: .

   ports:
    - "10080:4567"

   volumes:
     - .:/app
     - app-bundle:/usr/local/bundle

volumes:
 #Volumes boxed gem installed by Bundler
 app-bundle:
